using System.Security.Claims;

namespace StockFlow.API.Extensions;

// Provides helper methods to extract user-related data from JWT claims.
// Centralizing claim access avoids repeated claim parsing logic across controllers/services.
public static class UserExtensions
{
    // Extracts the authenticated user's ID from JWT claims.
    // Note: Assumes NameIdentifier claim is present and contains a valid integer.
    // If missing or invalid, an exception is thrown to prevent unauthorized access flow.
    public static int GetUserId(this ClaimsPrincipal user)
    {
        var userId = user.FindFirst(ClaimTypes.NameIdentifier)?.Value;

        if (string.IsNullOrWhiteSpace(userId))
        {
            throw new UnauthorizedAccessException("User id claim not found.");
        }

        // Parsing is safe under the assumption that JWT is generated by the system.
        return int.Parse(userId);
    }

    // Extracts the authenticated user's email from JWT claims.
    // Returns null if claim is not present.
    public static string? GetUserEmail(this ClaimsPrincipal user)
    {
        return user.FindFirst(ClaimTypes.Email)?.Value;
    }

    // Extracts the authenticated user's role from JWT claims.
    // Used for role-based access decisions where needed outside authorization attributes.
    public static string? GetUserRole(this ClaimsPrincipal user)
    {
        return user.FindFirst(ClaimTypes.Role)?.Value;
    }
}