namespace StockFlow.Domain.Entities;

// Represents the base class for all domain entities.
// Provides a common identity (primary key) across the domain model.
// Other shared fields (e.g., audit fields) can be added here as the system evolves.
public abstract class BaseEntity
{
    // Primary key used to uniquely identify an entity.
    // Value is generated by the database.
    public int Id { get; set; }
}